// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game.proto

/*
Package rummy is a generated protocol buffer package.

It is generated from these files:
	game.proto
	service.proto

It has these top-level messages:
	Meld
	PlayerState
	GameState
	GameEvent
	CreateGameRequest
	CreateGameResponse
	JoinGameRequest
	JoinGameResponse
	StartGameRequest
	StartGameResponse
	GetGameStateRequest
	GetHandCardsRequest
	GetHandCardsResponse
	SubscribeGameRequest
	PickUpStockRequest
	PickUpStockResponse
	PickUpDiscardRequest
	PickUpDiscardResponse
	PlayCardsRequest
	PlayCardsResponse
	DiscardCardRequest
	DiscardCardResponse
	CallRummyRequest
	CallRummyResponse
*/
package rummy

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import deck "github.com/timpalpant/rummy/deck"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GameState_TurnState int32

const (
	GameState_TURN_START      GameState_TurnState = 0
	GameState_PICKED_UP_CARDS GameState_TurnState = 1
	GameState_PLAYED_CARDS    GameState_TurnState = 2
)

var GameState_TurnState_name = map[int32]string{
	0: "TURN_START",
	1: "PICKED_UP_CARDS",
	2: "PLAYED_CARDS",
}
var GameState_TurnState_value = map[string]int32{
	"TURN_START":      0,
	"PICKED_UP_CARDS": 1,
	"PLAYED_CARDS":    2,
}

func (x GameState_TurnState) String() string {
	return proto.EnumName(GameState_TurnState_name, int32(x))
}
func (GameState_TurnState) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type GameEvent_Type int32

const (
	GameEvent_UNKNOWN_TYPE    GameEvent_Type = 0
	GameEvent_TURN_START      GameEvent_Type = 1
	GameEvent_PICK_UP_STOCK   GameEvent_Type = 2
	GameEvent_PICK_UP_DISCARD GameEvent_Type = 3
	GameEvent_PLAY_CARDS      GameEvent_Type = 4
	GameEvent_DISCARD         GameEvent_Type = 5
	GameEvent_GAME_OVER       GameEvent_Type = 6
)

var GameEvent_Type_name = map[int32]string{
	0: "UNKNOWN_TYPE",
	1: "TURN_START",
	2: "PICK_UP_STOCK",
	3: "PICK_UP_DISCARD",
	4: "PLAY_CARDS",
	5: "DISCARD",
	6: "GAME_OVER",
}
var GameEvent_Type_value = map[string]int32{
	"UNKNOWN_TYPE":    0,
	"TURN_START":      1,
	"PICK_UP_STOCK":   2,
	"PICK_UP_DISCARD": 3,
	"PLAY_CARDS":      4,
	"DISCARD":         5,
	"GAME_OVER":       6,
}

func (x GameEvent_Type) String() string {
	return proto.EnumName(GameEvent_Type_name, int32(x))
}
func (GameEvent_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type Meld struct {
	Cards []*deck.Card `protobuf:"bytes,1,rep,name=cards" json:"cards,omitempty"`
}

func (m *Meld) Reset()                    { *m = Meld{} }
func (m *Meld) String() string            { return proto.CompactTextString(m) }
func (*Meld) ProtoMessage()               {}
func (*Meld) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Meld) GetCards() []*deck.Card {
	if m != nil {
		return m.Cards
	}
	return nil
}

type PlayerState struct {
	Id             int32        `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name           string       `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Melds          []*Meld      `protobuf:"bytes,3,rep,name=melds" json:"melds,omitempty"`
	Rummies        []*deck.Card `protobuf:"bytes,4,rep,name=rummies" json:"rummies,omitempty"`
	NumCardsInHand int32        `protobuf:"varint,5,opt,name=num_cards_in_hand,json=numCardsInHand" json:"num_cards_in_hand,omitempty"`
	CurrentScore   int32        `protobuf:"varint,6,opt,name=current_score,json=currentScore" json:"current_score,omitempty"`
}

func (m *PlayerState) Reset()                    { *m = PlayerState{} }
func (m *PlayerState) String() string            { return proto.CompactTextString(m) }
func (*PlayerState) ProtoMessage()               {}
func (*PlayerState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PlayerState) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PlayerState) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlayerState) GetMelds() []*Meld {
	if m != nil {
		return m.Melds
	}
	return nil
}

func (m *PlayerState) GetRummies() []*deck.Card {
	if m != nil {
		return m.Rummies
	}
	return nil
}

func (m *PlayerState) GetNumCardsInHand() int32 {
	if m != nil {
		return m.NumCardsInHand
	}
	return 0
}

func (m *PlayerState) GetCurrentScore() int32 {
	if m != nil {
		return m.CurrentScore
	}
	return 0
}

type GameState struct {
	NumCardsInStock   int32               `protobuf:"varint,1,opt,name=num_cards_in_stock,json=numCardsInStock" json:"num_cards_in_stock,omitempty"`
	DiscardPile       []*deck.Card        `protobuf:"bytes,2,rep,name=discard_pile,json=discardPile" json:"discard_pile,omitempty"`
	AggregatedMelds   []*Meld             `protobuf:"bytes,3,rep,name=aggregated_melds,json=aggregatedMelds" json:"aggregated_melds,omitempty"`
	Players           []*PlayerState      `protobuf:"bytes,4,rep,name=players" json:"players,omitempty"`
	Turn              int32               `protobuf:"varint,6,opt,name=turn" json:"turn,omitempty"`
	CurrentPlayerTurn int32               `protobuf:"varint,7,opt,name=current_player_turn,json=currentPlayerTurn" json:"current_player_turn,omitempty"`
	TurnState         GameState_TurnState `protobuf:"varint,8,opt,name=turn_state,json=turnState,enum=rummy.GameState_TurnState" json:"turn_state,omitempty"`
	GameOver          bool                `protobuf:"varint,9,opt,name=game_over,json=gameOver" json:"game_over,omitempty"`
}

func (m *GameState) Reset()                    { *m = GameState{} }
func (m *GameState) String() string            { return proto.CompactTextString(m) }
func (*GameState) ProtoMessage()               {}
func (*GameState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GameState) GetNumCardsInStock() int32 {
	if m != nil {
		return m.NumCardsInStock
	}
	return 0
}

func (m *GameState) GetDiscardPile() []*deck.Card {
	if m != nil {
		return m.DiscardPile
	}
	return nil
}

func (m *GameState) GetAggregatedMelds() []*Meld {
	if m != nil {
		return m.AggregatedMelds
	}
	return nil
}

func (m *GameState) GetPlayers() []*PlayerState {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *GameState) GetTurn() int32 {
	if m != nil {
		return m.Turn
	}
	return 0
}

func (m *GameState) GetCurrentPlayerTurn() int32 {
	if m != nil {
		return m.CurrentPlayerTurn
	}
	return 0
}

func (m *GameState) GetTurnState() GameState_TurnState {
	if m != nil {
		return m.TurnState
	}
	return GameState_TURN_START
}

func (m *GameState) GetGameOver() bool {
	if m != nil {
		return m.GameOver
	}
	return false
}

type GameEvent struct {
	PlayerId int32          `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	Type     GameEvent_Type `protobuf:"varint,2,opt,name=type,enum=rummy.GameEvent_Type" json:"type,omitempty"`
	Cards    []*deck.Card   `protobuf:"bytes,3,rep,name=cards" json:"cards,omitempty"`
	Score    int32          `protobuf:"varint,4,opt,name=score" json:"score,omitempty"`
}

func (m *GameEvent) Reset()                    { *m = GameEvent{} }
func (m *GameEvent) String() string            { return proto.CompactTextString(m) }
func (*GameEvent) ProtoMessage()               {}
func (*GameEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GameEvent) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *GameEvent) GetType() GameEvent_Type {
	if m != nil {
		return m.Type
	}
	return GameEvent_UNKNOWN_TYPE
}

func (m *GameEvent) GetCards() []*deck.Card {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *GameEvent) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func init() {
	proto.RegisterType((*Meld)(nil), "rummy.Meld")
	proto.RegisterType((*PlayerState)(nil), "rummy.PlayerState")
	proto.RegisterType((*GameState)(nil), "rummy.GameState")
	proto.RegisterType((*GameEvent)(nil), "rummy.GameEvent")
	proto.RegisterEnum("rummy.GameState_TurnState", GameState_TurnState_name, GameState_TurnState_value)
	proto.RegisterEnum("rummy.GameEvent_Type", GameEvent_Type_name, GameEvent_Type_value)
}

func init() { proto.RegisterFile("game.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 596 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0xdf, 0x4e, 0xdb, 0x3e,
	0x14, 0xc7, 0x49, 0x9b, 0xd0, 0xe6, 0x14, 0x4a, 0x30, 0xbf, 0x9f, 0x14, 0xb1, 0x9b, 0xae, 0xdb,
	0x45, 0x11, 0x5b, 0x90, 0x98, 0x34, 0x69, 0x97, 0x5d, 0x5b, 0xb1, 0x8a, 0xd1, 0x56, 0x49, 0xd8,
	0xc4, 0x95, 0x65, 0x62, 0xab, 0x44, 0xe4, 0x9f, 0x1c, 0x07, 0xa9, 0xd2, 0x5e, 0x60, 0x0f, 0xb3,
	0x17, 0xd9, 0x53, 0x4d, 0xb6, 0x13, 0xca, 0x98, 0xb8, 0xa9, 0xdc, 0xef, 0xf9, 0xf8, 0x9c, 0xf3,
	0x3d, 0x3e, 0x01, 0x58, 0x93, 0x94, 0x79, 0x05, 0xcf, 0x45, 0x8e, 0x2c, 0x5e, 0xa5, 0xe9, 0xe6,
	0xf8, 0x74, 0x1d, 0x8b, 0xbb, 0xea, 0xd6, 0x8b, 0xf2, 0xf4, 0x4c, 0xc4, 0x69, 0x41, 0x92, 0x82,
	0x64, 0xe2, 0x4c, 0x05, 0xcf, 0x28, 0x8b, 0xee, 0xd5, 0x8f, 0xbe, 0x33, 0x1c, 0x81, 0x79, 0xc5,
	0x12, 0x8a, 0x06, 0x60, 0x45, 0x84, 0xd3, 0xd2, 0x35, 0x06, 0xed, 0x51, 0xef, 0x1c, 0x3c, 0xc5,
	0x4c, 0x08, 0xa7, 0xbe, 0x0e, 0x0c, 0x7f, 0x1b, 0xd0, 0x5b, 0x25, 0x64, 0xc3, 0x78, 0x20, 0x88,
	0x60, 0xa8, 0x0f, 0xad, 0x98, 0xba, 0xc6, 0xc0, 0x18, 0x59, 0x7e, 0x2b, 0xa6, 0x08, 0x81, 0x99,
	0x91, 0x94, 0xb9, 0xad, 0x81, 0x31, 0xb2, 0x7d, 0x75, 0x46, 0xaf, 0xc1, 0x4a, 0x59, 0x42, 0x4b,
	0xb7, 0xad, 0xb2, 0xf6, 0x3c, 0xd5, 0x84, 0x27, 0x2b, 0xfa, 0x3a, 0x82, 0xde, 0x42, 0x47, 0x8a,
	0x31, 0x2b, 0x5d, 0xf3, 0x9f, 0xd2, 0x4d, 0x08, 0x9d, 0xc0, 0x61, 0x56, 0xa5, 0x58, 0x75, 0x82,
	0xe3, 0x0c, 0xdf, 0x91, 0x8c, 0xba, 0x96, 0xaa, 0xdd, 0xcf, 0xaa, 0x54, 0xc2, 0xe5, 0x3c, 0xfb,
	0x42, 0x32, 0x8a, 0xde, 0xc0, 0x7e, 0x54, 0x71, 0xce, 0x32, 0x81, 0xcb, 0x28, 0xe7, 0xcc, 0xdd,
	0x55, 0xd8, 0x5e, 0x2d, 0x06, 0x52, 0x1b, 0xfe, 0x6a, 0x83, 0x7d, 0x41, 0x52, 0xa6, 0xad, 0x9c,
	0x02, 0xfa, 0x2b, 0x7b, 0x29, 0xf2, 0xe8, 0xbe, 0xb6, 0x76, 0xb0, 0x4d, 0x1f, 0x48, 0x19, 0xbd,
	0x87, 0x3d, 0x1a, 0x97, 0x92, 0xc5, 0x45, 0x9c, 0x48, 0xbf, 0xcf, 0xbb, 0xee, 0xd5, 0xf1, 0x55,
	0x9c, 0x30, 0xf4, 0x11, 0x1c, 0xb2, 0x5e, 0x73, 0xb6, 0x26, 0x82, 0x51, 0xfc, 0xe2, 0x34, 0x0e,
	0xb6, 0xd0, 0x95, 0x9a, 0xcb, 0x3b, 0xe8, 0x14, 0x6a, 0xda, 0xcd, 0x5c, 0x50, 0x8d, 0x3f, 0x79,
	0x03, 0xbf, 0x41, 0xe4, 0xf0, 0x45, 0xc5, 0xb3, 0xda, 0xab, 0x3a, 0x23, 0x0f, 0x8e, 0x9a, 0x41,
	0x68, 0x0c, 0x2b, 0xa4, 0xa3, 0x90, 0xc3, 0x3a, 0xa4, 0xb3, 0x85, 0x92, 0xff, 0x04, 0x20, 0x01,
	0x5c, 0xca, 0xd4, 0x6e, 0x77, 0x60, 0x8c, 0xfa, 0xe7, 0xc7, 0x75, 0xd1, 0xc7, 0x59, 0x79, 0x12,
	0xd5, 0xc5, 0x6d, 0xd1, 0x1c, 0xd1, 0x2b, 0xb0, 0xe5, 0x1e, 0xe2, 0xfc, 0x81, 0x71, 0xd7, 0x1e,
	0x18, 0xa3, 0xae, 0xdf, 0x95, 0xc2, 0xf2, 0x81, 0xf1, 0xe1, 0x67, 0xb0, 0x1f, 0x2f, 0xa1, 0x3e,
	0x40, 0x78, 0xed, 0x2f, 0x70, 0x10, 0x8e, 0xfd, 0xd0, 0xd9, 0x41, 0x47, 0x70, 0xb0, 0x9a, 0x4f,
	0x2e, 0x67, 0x53, 0x7c, 0xbd, 0xc2, 0x93, 0xb1, 0x3f, 0x0d, 0x1c, 0x03, 0x39, 0xb0, 0xb7, 0xfa,
	0x3a, 0xbe, 0x99, 0x4d, 0x6b, 0xa5, 0x35, 0xfc, 0xd9, 0xd2, 0xef, 0x35, 0x7b, 0x60, 0x99, 0x90,
	0xe5, 0x6a, 0x47, 0x8f, 0x1b, 0xd8, 0xd5, 0xc2, 0x9c, 0xa2, 0x13, 0x30, 0xc5, 0xa6, 0xd0, 0x7b,
	0xd8, 0x3f, 0xff, 0xff, 0x89, 0x01, 0x75, 0xd9, 0x0b, 0x37, 0x05, 0xf3, 0x15, 0xb2, 0x5d, 0xfa,
	0xf6, 0x0b, 0x4b, 0x8f, 0xfe, 0x03, 0x4b, 0x2f, 0x91, 0xa9, 0xaa, 0xe8, 0x3f, 0xc3, 0x1f, 0x60,
	0xca, 0x2c, 0xb2, 0xcf, 0xeb, 0xc5, 0xe5, 0x62, 0xf9, 0x7d, 0x81, 0xc3, 0x9b, 0xd5, 0xcc, 0xd9,
	0x79, 0x66, 0xcf, 0x40, 0x87, 0xb0, 0x2f, 0xed, 0x49, 0x73, 0x41, 0xb8, 0x9c, 0x5c, 0x3a, 0xad,
	0xc6, 0xb1, 0x94, 0xa6, 0xf3, 0x40, 0x1a, 0x74, 0xda, 0xf2, 0x9e, 0x74, 0x5c, 0xfb, 0x35, 0x51,
	0x0f, 0x3a, 0x4d, 0xd0, 0x42, 0xfb, 0x60, 0x5f, 0x8c, 0xaf, 0x66, 0x78, 0xf9, 0x6d, 0xe6, 0x3b,
	0xbb, 0xb7, 0xbb, 0xea, 0xcb, 0xfd, 0xf0, 0x27, 0x00, 0x00, 0xff, 0xff, 0x54, 0xc5, 0x18, 0xdb,
	0xfb, 0x03, 0x00, 0x00,
}
